### ISSUE TITLE
Aperture size should be odd between 3 and 7

### ISSUE THREAD

**Issue by graiSoft1982** [shimat/opencvsharp_samples#26]
Start CameraOpenCv.Exe sample and change apperture size to 4 and the program throw an exception. 
Aperture size should be odd between 3 and 7
Filename:C:\projects\opencv-files\opencv\modules\imgproc\src\canny.cpp

"  at OpenCvSharp.NativeMethods.<>c.<.cctor>b__1591_0(ErrorCode status, String funcName, String errMsg, String fileName, Int32 line, IntPtr userData)
   at OpenCvSharp.NativeMethods.imgproc_Canny1(IntPtr src, IntPtr edges, Double threshold1, Double threshold2, Int32 apertureSize, Int32 l2Gradient)
   at OpenCvSharp.Cv2.Canny(InputArray src, OutputArray edges, Double threshold1, Double threshold2, Int32 apertureSize, Boolean L2gradient)
   at SDKTemplate.OcvOp.Canny(SoftwareBitmap input, SoftwareBitmap output, Algorithm algorithm) in C:\Users\Username\Downloads\opencvsharp_samples-master\CameraOpenCV\OcvOp.cs:line 145
   at SDKTemplate.Scenario1_ExampleOperations.ColorFrameReader_FrameArrivedAsync(MediaFrameReader sender, MediaFrameArrivedEventArgs args) in C:\Users\Username\Downloads\opencvsharp_samples-master\CameraOpenCV\Scenario1_ExampleOperations.xaml.cs:line 217"

**Comment by shimat** [comment]
This exception originated in the UWP sample project (`CameraOpenCV`), which was removed in acc739f ("Migrate samples to OpenCvSharp5 (OpenCV 5.x), drop legacy project formats") — UWP/net48-style projects can't consume OpenCvSharp5 (net8.0+ only), so it wasn't ported forward. Closing as the affected code no longer exists in this repo. The old OpenCvSharp4-based state is preserved on the `4.x` branch if you need a reference.
